[package]
name = "sheldons-favorite-game"
version = "0.1.0"
edition = "2021"
authors = ["Sagi Sarussi <sagis@sagis.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
